version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: mongodb_nest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: 
      context: ./nestjs2
    container_name: nestjs_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mongodb://db:27017/nest_db 
    volumes:
      - ./nestjs2:/app
      - /app/node_modules

  frontend:
    build: 
      context: ./nextjs1
    container_name: nextjs_front
    ports:
      - "5000:5000" 
    depends_on:
      - backend
    volumes:
      - ./nextjs1:/app
      - /app/node_modules

volumes:
  mongo_data: